version: "3.3"
services:
  web:
    build: web
    ports:
      - "80:8000"
    volumes:
      - ./web:/app
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cs_doc
      - POSTGRES_PASSWORD=cs_doc_sc66
      - POSTGRES_DB=db_cs_doc
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=cs_doc@cmu.ac.th
      - PGADMIN_DEFAULT_PASSWORD=cs-doc66
    depends_on:
      - db

volumes:
  postgres_data:
